#!/usr/bin/env bash

DATADIRECTORY=/home/stenger/stenger_data/99_software/angsd

cd $DATADIRECTORY

# For created a genotyplikelihood dendrogram, first we need the identity-by-state (IBS) matrix generated by ANGSD.
# See this paper:
# https://www.biorxiv.org/content/10.1101/2020.02.26.956680v1.full.pdf
# https://doi.org/10.1101/2020.02.26.956680
# Co-recruitment of relatives in a broadcast-spawning coral (Acropora hyacinthus) facilitates emergence of an inbred, genetically distinct group within a panmictic population
# from Sarah Barfield, Sarah W. Davies, Mikhail V. Matz

# For IBS by ANSGD see
# http://www.popgen.dk/angsd/index.php/Relatedness#How_to_get_the_IBS_pattern
# http://www.popgen.dk/angsd/index.php/Genotype_Distribution

# Estimate all 10 genotype fractions for each of the 12 individuals
misc/ibs -f genolike.glf.gz -nInd 12 -o all
# The output file is all.ibs
